export const arrayOfEnvironments = [
    {
        id:1,
        Name: "PEP ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UID:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:2,
        Name: "PPM ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UID:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:3,
        Name: "UiPath ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UID:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:4,
        Name: "Tidium ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UID:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:5,
        Name: "ODM ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UID:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:6,
        Name: "TDM ",
        image:"./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UID:'',
        Password:'',
        IsSourcePrimary:'',
    },
];