import React from 'react'

export const practiceArr = [
    {
        id:1,
        App:1,
        Name: "PEP ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UApp:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:2,
        App:1,
        Name: "PEP ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UApp:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:3,
        App:2,
        Name: "PPM ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UApp:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:4,
        App:2,
        Name: "UiPath ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UApp:'',
        Password:'',
        IsSourcePrimary:'',
    },
    {
        id:5,
        App:3,
        Name: "Tidium ",
        image: "./images/database1.jpg",
        Type:'',
        DataSourceLink:'',
        UApp:'',
        Password:'',
        IsSourcePrimary:'',
    },
];
